Module2 task1
htmlacademy-vue/859219-pizza-1 pull request #2
Opened 2023-02-08 06:37 UTC by Ekzaton

2023-02-09 10:55 UTC, S-le commented on src/frontend/src/views/Index.vue
> +    },
Один универсальный работающий метод в компонете это, конечно, хорошо. Но чем больше метод и чем больше он выполняет действий, тем сложнее в нем разобраться. Даже его автору через какое-то время)). А также такой метод сложнее описывать тестами. 
Возможно, стоит разделить его на несколько методов. Например `changeSize(size)`  и привязать его к событию **change-selected-item** компонента _BuilderSizeSelector_. Таким образом методов станет больше, но каждый будет иметь свою область ответственности. Изменения, в несенные в такой метод, не повлияют на поведение других компонентов.

2023-02-09 14:00 UTC, Ekzaton commented on src/frontend/src/views/Index.vue
> +    },
Хорошо, сделаю отдельные методы для изменения теста/размера/соуса/ингредиентов пиццы

2023-02-09 14:11 UTC, S-le requested changes
Хорошо проделанная работа! Обрати внимание на ТЗ к заданию. Сумма не отображается в шапке сайта. Это одна ошибка, которую ты быстро исправишь.
Все остальные комментарии больше про оптимизацию. Внимательно прочитай.
Если будут вопросы, задавай.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      Size,
Поскольку Size в компонте не изменяется, а используется только для чтения, стоит сделать её вычисляемым свойством.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      sizes: {
В объектe _items_ присутствует лишнее свойство _sizes_. Оно не приведет к ошибке, в просто будет проигнорировано. Про синтаксис **props** можно почитать в [документации](https://ru.vuejs.org/v2/api/#props).

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +  props: {
Возможно, следует оптимизировать передаваемы входные параметры. В логике компонента из объекта **items** используется только массив **sizes**.  Следовательно и передавать во входные параметры следует не весь объект items, в только массив sizes. 
Тоже самое касается и **selectedItems**.  Если используется только selectedItems.size.id, то передать следует, например, selectedSize - объект выделенного размера или selectedSizeId - id выбранного размера.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +            $emit('change-selected-item', {
Как описал в комментариях в Index.vue, если изменить реализацию в родительском компоненте, тогда можно не передавать в **$emit** свойство _name_. Это упростит реализацию и измбавит от потециальной ошибки, ведь в слове "size" можно сделать опечатку или имя изменится в родительском компоненте.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      Dough,
Dough используется только для чтения, лучше сделать его вычисляемым.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      dough: {
В объектe items присутствует лишнее свойство **dough**. Оно не приведет к ошибке, в просто будет проигнорировано. Про синтаксис props можно почитать в [документации](https://ru.vuejs.org/v2/api/#props).

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +  props: {
Следует оптимизировать входные параметры компонента, чтобы не передавать лишние данные. Подробнее расписал в комментарии к **props** в компоненте _BuilderSizeSelector.vue_.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/views/Index.vue
> +  <AppLayout>
Не передается обязательное свойство **totalPrice**. В компонете _AppLayout_ присутствует свойство totalPrice и оно отмечено как required. Из-за этого в шапке сайта не показывается итоговая стоимость. 
Расчет итоговой стоимости был вынесен в _BuilderPriceCounter.vue_, поэтому необходимо пересмотреть место в котором должен происходить расчет.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    items: {
Входной параметр **items** не используется в компоненте, но помечен как обязательный.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  <Drop @drop="changeCounterValue">
В пункте 3.2.4 технической документации к заданию:
> Drag-n-drop — пользователь хватает мышкой ингредиент и тянет его на пиццу.
Будет лучше, если обернуть в Drop блок с самой пиццей.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +<template>
Компонент можно разделить на логические части. Это не ошибка, компонент рабочий.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    items: {
Ошибки в передаче объектов во входные параметры. [https://ru.vuejs.org/v2/api/#props](https://ru.vuejs.org/v2/api/#props)

Следует оптимизировать входные параметры компонента, чтобы не передавать лишние данные. Подробнее расписал в комментарии к **props** в компоненте *BuilderSizeSelector.vue*.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      Ingredient,
Не используется в компоненте, лучше удалить.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +    item: {
Ошибки в передаче объектов во входные параметры. https://ru.vuejs.org/v2/api/#props

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +    selectedItems: {
Поскольку из входного параметра **selectedItems** используется только свойство **selectedItems.ingredients**, то лучше его и передавать в компонент.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +        this.selectedItems.ingredients.find((item) => item.id === this.item.id)
Код `this.selectedItems.ingredients.find((item) => item.id === this.item.id)` используется несколько раз в компоненте, но делает одно и тоже. Возможно, стоит сделать вычесляемое свойство **selectedIngredient**, а потом использовать его.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/common/components/SelectorItem.vue
> +      Ingredient,
Т.к. **Ingredient** используется только для чтения, лучше сделать вычесляемым свойством.

2023-02-09 14:11 UTC, S-le commented on src/frontend/src/common/components/SelectorItem.vue
> +    item: {
Ошибка в синтаксисе объекта входного параметра. https://ru.vuejs.org/v2/api/#props

2023-02-10 07:11 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      Size,
Перенёс Size в computed

2023-02-10 07:12 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +      sizes: {
Поправил props

2023-02-10 07:12 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +  props: {
Изменил props

2023-02-10 07:13 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      Dough,
Перенёс  Dough в computed

2023-02-10 07:14 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      dough: {
Поправил props

2023-02-10 07:14 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +  props: {
Изменил props

2023-02-10 07:16 UTC, Ekzaton commented on src/frontend/src/views/Index.vue
> +  <AppLayout>
1. Перенёс расчёт в Index
2. Передал totalPrice в AppLayout

2023-02-10 07:17 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +  <Drop @drop="changeCounterValue">
1. Вынес блок с пиццей в отдельный компонент BuilderPizzaFoundation
2. Обернул содержимое блока в Drop

2023-02-10 07:17 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    items: {
Поправил props

2023-02-10 07:18 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +<template>
Перенёс содержимое в компоненты BuilderPizzaName, BuilderPizzaFoundation и BuilderSubmitButton

2023-02-10 07:19 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    items: {
Поправил props

2023-02-10 07:19 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      Ingredient,
Поправил props

2023-02-10 07:19 UTC, Ekzaton commented on src/frontend/src/common/components/ItemCounter.vue
> +    selectedItems: {
Изменил props

2023-02-10 07:20 UTC, Ekzaton commented on src/frontend/src/common/components/ItemCounter.vue
> +        this.selectedItems.ingredients.find((item) => item.id === this.item.id)
Добавил вычисляемое свойство pizzaIngredient

2023-02-10 07:21 UTC, Ekzaton commented on src/frontend/src/common/components/SelectorItem.vue
> +      Ingredient,
Перенёс Ingredient в computed

2023-02-10 07:21 UTC, Ekzaton commented on src/frontend/src/common/components/SelectorItem.vue
> +    item: {
Поправил props

2023-02-10 07:21 UTC, Ekzaton commented on src/frontend/src/common/components/ItemCounter.vue
> +    item: {
Поправил props

2023-02-11 11:05 UTC, S-le requested changes
👍 Отлично проделанная работа над ошибками!

В документации Vue есть раздел "Рекомендации", рекомендую посмотреть его в свободное время. Старайся располагать опции компонентов в одном порядке. Это твой проект и ты можешь определить этот порядок сам. Например, такой порядок рекомендован [документацией](https://ru.vuejs.org/v2/style-guide/#%D0%9F%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D0%BF%D1%86%D0%B8%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%D0%B0-%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F).

Молодец! Продолжай в том же духе! Жду следующую домашку.

2023-02-11 11:05 UTC, S-le commented on src/frontend/src/layouts/AppLayout.vue
> +<style scoped>
Обрати внимание, что в проекте используются файлы стиля SCSS - это препроцессор. Однофайловый компонент во Vue настроен по умолчанию для работы с CSS файлами. Следует явно указать _lang="scss"_ в секции _style_ `<style scoped lang="scss">`

2023-02-11 11:05 UTC, merged