14. Refactored private layout
htmlacademy-vue/859219-pizza-1 pull request #4
Opened 2023-02-15 20:26 UTC by Ekzaton

2023-02-22 11:57 UTC, S-le requested changes
Работы выполнена на отлично! Так держать!

Я оставил комментарии к коду. Но это даже не замечания, а моменты для ознакомления и мысли. Есть несколько ссылок на документацию, ознакомься с ними, это будет полезно.

Внимательно изучи следующую тему. Там будет работа с сервером. После его выполнения работа должна соответствовать всему техническому заданию.

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/layouts/components/AppLayoutHeader.vue
> +    ...mapGetters("Auth", ["isAuthorized"]),
"user" и "isAuthorized" возвращают одно и тоже значение.

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/store/modules/auth.js
> +      return state.user;
Поскольку getter *isAuthorized* используется для проверки авторизован ли пользователь, логично изменить его, чтобы он возвращал boolean значение.

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/store/modules/builder.js
> +      state.pizza.value = payload.value;
**value** переводится как *значение*, а тут имеется ввиду количество (*quantity*). Не запутайся.

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/store/modules/builder.js
> +      state.pizza.id = payload.id;
Добавление и удаление полей объекта для Vue 2 очень опасная штука. Vue обходит все поля объекта в момент кго создания и делает их реактивными (подробнее можно прочитать в [документации](https://ru.vuejs.org/v2/guide/reactivity.html)). Поэтому когда поля в объект просто добавляются или удаляются, как принято в JS, то система реактивности может не обнаружить эти изменения. В связи с этим есть методы [Vue.set](https://ru.vuejs.org/v2/api/#Vue-set) и [Vue.delete](https://ru.vuejs.org/v2/api/#Vue-delete).
Также можно сделать это при помощи деструктуризации или *Object.assign* `state.pizza = { ...payload }`

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/store/modules/builder.js
> +      delete state.pizza.id;
[Vue.delete](https://ru.vuejs.org/v2/api/#Vue-delete)

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderPizzaName.vue
> +      @input="changePizzaName($event.target.value)"
На заметку! Можно реализовать через [**v-model**](https://v3.vuex.vuejs.org/ru/guide/forms.html#%D0%B4%D0%B2%D1%83%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D1%8F%D0%B5%D0%BC%D1%8B%D0%B5-%D1%81%D0%B2%D0%BE%D0%B8%D1%81%D1%82%D0%B2%D0%B0).

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/modules/cart/components/CartAdditionsSelector.vue
> +            alt="Coca-Cola 0,5 литра"
*alt* тоже необходимо изменять для каждого элемента.

2023-02-22 11:57 UTC, S-le commented on src/frontend/src/modules/cart/components/CartDelivery.vue
> +          this.setFormFieldValue({ name: "street", value: "" });
Поскольку в компоненте есть *streetValue* с сеттером, то можно исопльзовать его `this.streetValue = ""`.

2023-02-22 11:58 UTC, merged

2023-03-07 20:22 UTC, Ekzaton commented on src/frontend/src/layouts/components/AppLayoutHeader.vue
> +    ...mapGetters("Auth", ["isAuthorized"]),
Исправил

2023-03-07 20:22 UTC, Ekzaton commented on src/frontend/src/store/modules/auth.js
> +      return state.user;
Исправил

2023-03-07 20:25 UTC, Ekzaton commented on src/frontend/src/store/modules/builder.js
> +      state.pizza.value = payload.value;
Изменил на value на count для всех сущностей, у которых есть количество

2023-03-07 20:26 UTC, Ekzaton commented on src/frontend/src/store/modules/builder.js
> +      state.pizza.id = payload.id;
Заменил прямое создание и удаление свойств на Vue.set  и Vue.delete

2023-03-07 20:27 UTC, Ekzaton commented on src/frontend/src/modules/builder/components/BuilderPizzaName.vue
> +      @input="changePizzaName($event.target.value)"
Реализовал

2023-03-07 20:27 UTC, Ekzaton commented on src/frontend/src/modules/cart/components/CartAdditionsSelector.vue
> +            alt="Coca-Cola 0,5 литра"
Поправил

2023-03-07 20:27 UTC, Ekzaton commented on src/frontend/src/modules/cart/components/CartDelivery.vue
> +          this.setFormFieldValue({ name: "street", value: "" });
Поправил